version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: motus-redis
    ports:
      - "6380:6379"
    volumes:
      - ./data/redis:/data
    networks:
      - motus-network
    command: redis-server --appendonly yes


  redisinsight:
    image: redislabs/redisinsight:latest
    container_name: motus-redisinsight
    ports:
      - "8001:8001"
    depends_on:
      - redis
    volumes:
      - ./data/redisinsight:/db
    restart: always
    networks:
      - motus-network

networks:
  motus-network:
    driver: bridge
